bgame/bgame/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('game/', include('game.urls')),
    path('admin/', admin.site.urls),
]

bgame/game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    # /game/
    path('', views.index, name='index'),
    path('weapons/', views.weapons, name='weapons-index'),
    path('weapons/create/', views.weapons_create, name='weapons-create'),
    path('weapons/store/', views.weapons_store, name='weapons-store'),
    path('armors/', views.armors, name='armors-index'),
    path('armors/create/', views.armors_create, name='armors-create'),
    path('armors/store/', views.armors_store, name='armors-store'),
    path('characters/', views.characters, name='characters-index'),
    path('characters/create/', views.characters_create, name='characters-create'),
    path('characters/store/', views.characters_store, name='characters-store'),
]

bgame/game/models.py
from django.db import models
from django.forms import CharField


# Create your models here.
class Weapon(models.Model):
    name = models.CharField(max_length=200)
    damage = models.IntegerField()
    icon_path = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Armor(models.Model):
    name = models.CharField(max_length=200)
    defense = models.IntegerField()
    icon_path = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Spell(models.Model):
    name = models.CharField(max_length=200)
    mana = models.IntegerField()
    damage = models.IntegerField()
    icon_path = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class TypeCharacter(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    icon_path = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Character(models.Model):
    name = models.CharField(max_length=200)
    hp = models.IntegerField()
    mana = models.IntegerField()
    type_character = models.ForeignKey(TypeCharacter, on_delete=models.CASCADE, default=1)
    weapon = models.ForeignKey(Weapon, on_delete=models.SET_NULL, null=True)
    armor = models.ForeignKey(Armor, on_delete=models.SET_NULL, null=True) 
    spell = models.ForeignKey(Spell, on_delete=models.SET_NULL, blank=True, null=True) 

    def __str__(self):
        return self.name

bgame/game/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from game.models import Character, Weapon, Armor, Spell, TypeCharacter

# Create your views here.
def index(request):
    characters = Character.objects.all()
    return render(request, 'index.html', {'characters': characters})

def weapons(request):
    weapons = Weapon.objects.all()
    return render(request, 'weapons/index.html', {'weapons': weapons})

def weapons_create(request):
    return render(request, 'weapons/create.html')

# POST 
def weapons_store(request):
    Weapon.objects.create(name=request.POST["name"], damage=request.POST["damage"], icon_path=request.POST["icon_path"])
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('game:weapons-index'))

def armors(request):
    armors = Armor.objects.all()
    return render(request, 'armors/index.html', {'armors': armors})

def armors_create(request):
    return render(request, 'armors/create.html')

# POST 
def armors_store(request):
    Armor.objects.create(name=request.POST["name"], defense=request.POST["defense"], icon_path=request.POST["icon_path"])
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('game:armors-index'))

def characters(request):
    characters = Character.objects.all()
    return render(request, 'characters/index.html', {'characters': characters})

def characters_create(request):
    context = {"armors": Armor.objects.all(), "weapons": Weapon.objects.all(), "spells": Spell.objects.all(), "types_character": TypeCharacter.objects.all()}
    return render(request, 'characters/create.html', context)

# POST 
def characters_store(request):
    Character.objects.create(
        name=request.POST["name"],
        hp=request.POST["hp"],
        mana=request.POST["mana"],
        type_character=TypeCharacter.objects.get(pk=request.POST["type_character"]),
        weapon=Weapon.objects.get(pk=request.POST["weapon"]), 
        armor=Armor.objects.get(pk=request.POST["armor"]),
        spell=Spell.objects.get(pk=request.POST["spell"])
    )
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('game:characters-index'))

bgame/game/templates/armors/create.html
{% include 'layout/header.html' %}
<body>
    {% load static %}
    {% include 'layout/navbar.html' %}

    <div class="container">
        <h1 class="mt-4">Add an armor</h1>

        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{error_message}}
        </div>
        {% endif %}

        <form action="{% url 'game:armors-store' %}" method="post">
            {% csrf_token %}
            <div class="form-group my-2">
              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Enter a name" required>
            </div>
            <div class="form-group my-2">
                <label for="damage">Defense</label>
                <input type="number" class="form-control" id="defense" name="defense" required>
            </div>
            <div class="form-group my-2">
                <label for="icon_path">Icon path</label>
                <input type="text" class="form-control" id="icon_path" name="icon_path" required>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Submit</button>
          </form>
    </div>
</body>
</html>

bgame/game/templates/armors/index.html
{% include 'layout/header.html' %}
<body>
    {% load static %}
    {% include 'layout/navbar.html' %}

    <div class="container">
        <h1 class="mt-4">Armors</h1>
        <a class="btn btn-success" href="{% url 'game:armors-create' %}" role="button">Add an armor</a>
        
        {% for armor in armors %}
        <div class="my-4">
            <div class="my-2">
                <p><strong>Armor:</strong> {{armor.name}} ({{armor.damage}} defense)</p>
                <img src="{% static 'game/armors/' %}{{armor.icon_path}}" width="30" height="30">
            </div>
        </div>
        <hr/>
        {% endfor %}
    </div>

</body>
</html>

bgame/game/templates/characters/create.html
{% include 'layout/header.html' %}
<body>
    {% load static %}
    {% include 'layout/navbar.html' %}

    <div class="container">
        <h1 class="mt-4">Add a character</h1>

        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{error_message}}
        </div>
        {% endif %}

        <form action="{% url 'game:characters-store' %}" method="post">
            {% csrf_token %}
            <div class="form-group my-2">
              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Enter a name" required>
            </div>
            <div class="form-group my-2">
                <label for="name">HP</label>
                <input type="number" class="form-control" id="hp" name="hp" placeholder="Enter hp" required>
            </div>
            <div class="form-group my-2">
                <label for="name">Mana</label>
                <input type="number" class="form-control" id="mana" name="mana" placeholder="Enter mana" required>
            </div>
            <div class="form-group my-2">
                <label for="weapon">Weapon</label>
                <select class="form-control" id="weapon" name="weapon"> 
                    {% for weapon in weapons %}
                        <option value="{{weapon.id}}">{{weapon.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group my-2">
                <label for="armor">Armor</label>
                <select class="form-control" id="armor" name="armor">
                    {% for armor in armors %}
                        <option value="{{armor.id}}">{{armor.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group my-2">
                <label for="spell">Spell</label>
                <select class="form-control" id="spell" name="spell">
                    <option></option>
                    {% for spell in spells %}
                        <option value="{{spell.id}}">{{spell.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group my-2">
                <label for="type_character">Type character</label>
                <select class="form-control" id="type_character" name="type_character">
                    {% for type_character in types_character %}
                        <option value="{{type_character.id}}">{{type_character.name}}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary mt-2">Submit</button>
          </form>
    </div>
</body>
</html>

bgame/game/templates/characters/index.html
{% include 'layout/header.html' %}
<body>
    {% load static %}
    {% include 'layout/navbar.html' %}

    <div class="container">
        <h1 class="mt-4">Characters</h1>
        <a class="btn btn-success" href="{% url 'game:characters-create' %}" role="button">Add a character</a>
        
        {% for character in characters %}
        <div class="my-4">
            <h4>{{character.name}}</h4>
            <h6 class="text-secondary">{{character.type_character.name|upper}}</h6>
            <p><strong>HP:</strong> {{character.hp}}</p>
            <p><strong>Mana:</strong> {{character.mana}}</p>
            <div class="my-2">
                <p class="mb-2"><strong>Weapon:</strong> {{character.weapon.name}} ({{character.weapon.damage}} damage)</p>
                <img src="{% static 'game/weapons/' %}{{character.weapon.icon_path}}" width="30" height="30">
            </div>
            <div class="my-2">
                <p class="mb-2"><strong>Armor:</strong> {{character.armor.name}}</p>
                <img src="{% static 'game/armors/' %}{{character.armor.icon_path}}" width="30" height="30">
            </div>
            {% if character.spell %}
            <div class="my-2">
                <p class="mb-2"><strong>Spell:</strong> {{character.spell.name}} ({{character.spell.mana}} mana)</p>
                <img src="{% static 'game/spells/' %}{{character.spell.icon_path}}" width="30" height="30">
            </div>
            {% endif %}
        </div>
        <hr/>
        {% endfor %}
    </div>

</body>
</html>

bgame/game/templates/index.html
{% include 'layout/header.html' %}
<body>
    {% load static %}
    {% include 'layout/navbar.html' %}

    <div class="container">
        {% for character in characters %}
        <div class="my-4">
            <h4>{{character.name}}</h4>
            <h6 class="text-secondary">{{character.type_character.name|upper}}</h6>
            <p><strong>HP:</strong> {{character.hp}}</p>
            <p><strong>Mana:</strong> {{character.mana}}</p>
            <div class="my-2">
                <p class="mb-2"><strong>Weapon:</strong> {{character.weapon.name}} ({{character.weapon.damage}} damage)</p>
                <img src="{% static 'game/weapons/' %}{{character.weapon.icon_path}}" width="30" height="30">
            </div>
            <div class="my-2">
                <p class="mb-2"><strong>Armor:</strong> {{character.armor.name}}</p>
                <img src="{% static 'game/armors/' %}{{character.armor.icon_path}}" width="30" height="30">
            </div>
            {% if character.spell %}
            <div class="my-2">
                <p class="mb-2"><strong>Spell:</strong> {{character.spell.name}} ({{character.spell.mana}} mana)</p>
                <img src="{% static 'game/spells/' %}{{character.spell.icon_path}}" width="30" height="30">
            </div>
            {% endif %}
        </div>
        <hr/>
        {% endfor %}
    </div>
    
</body>
</html>

bgame/game/templates/layout/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Battle Game</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

bgame/game/templates/layout/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'game:index' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'game:weapons-index' %}">Weapons</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'game:armors-index' %}">Armors</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'game:characters-index' %}">Characters</a>
        </li>
    </ul>
</nav>

bgame/game/templates/weapons/create.html
{% include 'layout/header.html' %}
<body>
    {% load static %}
    {% include 'layout/navbar.html' %}

    <div class="container">
        <h1 class="mt-4">Add a weapon</h1>

        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{error_message}}
        </div>
        {% endif %}

        <form action="{% url 'game:weapons-store' %}" method="post">
            {% csrf_token %}
            <div class="form-group my-2">
              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Enter a name" required>
            </div>
            <div class="form-group my-2">
                <label for="damage">Damage</label>
                <input type="number" class="form-control" id="damage" name="damage" required>
            </div>
            <div class="form-group my-2">
                <label for="icon_path">Icon path</label>
                <input type="text" class="form-control" id="icon_path" name="icon_path" required>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Submit</button>
          </form>
    </div>
</body>
</html>

bgame/game/templates/weapons/index.html
{% include 'layout/header.html' %}
<body>
    {% load static %}
    {% include 'layout/navbar.html' %}

    <div class="container">
        <h1 class="mt-4">Weapons</h1>
        <a class="btn btn-success" href="{% url 'game:weapons-create' %}" role="button">Add a weapon</a>
        
        {% for weapon in weapons %}
        <div class="my-4">
            <div class="my-2">
                <p><strong>Weapon:</strong> {{weapon.name}} ({{weapon.damage}} damage)</p>
                <img src="{% static 'game/weapons/' %}{{weapon.icon_path}}" width="30" height="30">
            </div>
        </div>
        <hr/>
        {% endfor %}
    </div>

</body>
</html>